- name: Build and Deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_DESERT_0EB7D6B10 }}
    action: "upload"
    app_location: "/"
    api_location: ""
    output_location: "."
    skip_app_build: true  # Skip build step for static site
